version: '2'

services:

    elastic-search:
        container_name: wswork_elastic_search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        environment:
            - "discovery.type=single-node"
        network_mode: host

    kibana:
        container_name: wswork_kibana
        image: docker.elastic.co/kibana/kibana:7.0.0
        environment:
                SERVER_NAME: localhost
                ELASTICSEARCH_URL: http://localhost:9200
        network_mode: host
        
    logstash:
        container_name: wswork_logstash
        image: docker.elastic.co/logstash/logstash:7.0.0
        volumes:
            - ./config/logstash-spring-cloud.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
        network_mode: host
networks:
    wswork_network:
        driver: bridge
